### ISSUE TITLE
Когда обнова???

### ISSUE THREAD

**Issue by ScriptedSnark** [zipmishahl2/mishaModhl2#5]
Очень жду недождусь новую версию!

**Comment by zipmishahl2** [comment]
Привет, уже сегодня планируем выпустить @ScriptedSnark 
уважением от @zipmishahl2 @MishaHalf-life-mod

**Comment by ScriptedSnark** [comment]
Спасибо за ответ!!!

**Comment by rogender** [comment]
так а когда обнова то
